baseurl: https://blog.joaquin-caro.es
languageCode: es-es
theme: hugo-theme-stack
paginate: 5
title: Joaquín Caro

languages:
    es:
        languageName: Spanish
        title: Joaquín Caro
        description: Mi Cuaderno de bitácora
        weight: 1


# GA Tracking ID
googleAnalytics: G-H13WFLX5M2

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: es

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2018
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 👨🏻‍💻
        subtitle: Mi Cuaderno de bitácora.
        avatar:
            enabled: true
            local: true
            src: img/main.jpg

    article:
        math: false
        toc: true
        readingTime: true

    widgets:
        homepage:
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/jcaromiq
          params:
              icon: github
        - identifier: linkedin
          name: Linkedin
          url: https://linkedin.com/in/joaquincaro
          params:
              icon: linkedin
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/joaquin_caro
          params:
              icon: twitter
        - identifier: gitlab
          name: Gitlab
          url: https://gitlab.com/jcaromiq
          params:
              icon: gitlab
        - identifier: dev
          name: Dev.to
          url: https://dev.to/jcaromiq
          params:
              icon: dev

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
